// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginUp_MessageEnum int32

const (
	LoginUp_First     LoginUp_MessageEnum = 0
	LoginUp_CommondId LoginUp_MessageEnum = 10001
)

var LoginUp_MessageEnum_name = map[int32]string{
	0:     "First",
	10001: "CommondId",
}

var LoginUp_MessageEnum_value = map[string]int32{
	"First":     0,
	"CommondId": 10001,
}

func (x LoginUp_MessageEnum) String() string {
	return proto.EnumName(LoginUp_MessageEnum_name, int32(x))
}

func (LoginUp_MessageEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0, 0}
}

type LoginDown_MessageEnum int32

const (
	LoginDown_First     LoginDown_MessageEnum = 0
	LoginDown_CommondId LoginDown_MessageEnum = 10002
)

var LoginDown_MessageEnum_name = map[int32]string{
	0:     "First",
	10002: "CommondId",
}

var LoginDown_MessageEnum_value = map[string]int32{
	"First":     0,
	"CommondId": 10002,
}

func (x LoginDown_MessageEnum) String() string {
	return proto.EnumName(LoginDown_MessageEnum_name, int32(x))
}

func (LoginDown_MessageEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1, 0}
}

//------------------------
//登录
type LoginUp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUp) Reset()         { *m = LoginUp{} }
func (m *LoginUp) String() string { return proto.CompactTextString(m) }
func (*LoginUp) ProtoMessage()    {}
func (*LoginUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *LoginUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUp.Unmarshal(m, b)
}
func (m *LoginUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUp.Marshal(b, m, deterministic)
}
func (m *LoginUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUp.Merge(m, src)
}
func (m *LoginUp) XXX_Size() int {
	return xxx_messageInfo_LoginUp.Size(m)
}
func (m *LoginUp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUp proto.InternalMessageInfo

type LoginDown struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginDown) Reset()         { *m = LoginDown{} }
func (m *LoginDown) String() string { return proto.CompactTextString(m) }
func (*LoginDown) ProtoMessage()    {}
func (*LoginDown) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *LoginDown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginDown.Unmarshal(m, b)
}
func (m *LoginDown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginDown.Marshal(b, m, deterministic)
}
func (m *LoginDown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginDown.Merge(m, src)
}
func (m *LoginDown) XXX_Size() int {
	return xxx_messageInfo_LoginDown.Size(m)
}
func (m *LoginDown) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginDown.DiscardUnknown(m)
}

var xxx_messageInfo_LoginDown proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("msg.LoginUp_MessageEnum", LoginUp_MessageEnum_name, LoginUp_MessageEnum_value)
	proto.RegisterEnum("msg.LoginDown_MessageEnum", LoginDown_MessageEnum_name, LoginDown_MessageEnum_value)
	proto.RegisterType((*LoginUp)(nil), "msg.LoginUp")
	proto.RegisterType((*LoginDown)(nil), "msg.LoginDown")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x32, 0xe6, 0x62,
	0xf7, 0x01, 0x89, 0x85, 0x16, 0x28, 0x69, 0x70, 0x71, 0xfb, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7,
	0xba, 0xe6, 0x95, 0xe6, 0x0a, 0x71, 0x72, 0xb1, 0xba, 0x65, 0x16, 0x15, 0x97, 0x08, 0x30, 0x08,
	0xf1, 0x71, 0x71, 0x3a, 0xe7, 0xe7, 0xe6, 0xe6, 0xe7, 0xa5, 0x78, 0xa6, 0x08, 0x4c, 0xf4, 0x53,
	0x32, 0xe5, 0xe2, 0x04, 0x6b, 0x72, 0xc9, 0x2f, 0xcf, 0x23, 0x56, 0xdb, 0x24, 0xbf, 0x24, 0x36,
	0xb0, 0xbd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0x7d, 0x57, 0x85, 0x86, 0x00, 0x00,
	0x00,
}
